version: 1.0.{build}

branches:
  only:
    - master
    - VS2017

image: Visual Studio 2017
clone_folder: c:\projects\blackbone

platform: 
  - Win32
  - x64

configuration: 
  - Debug
  - Release
  
build:
  parallel: true
  project: BlackBone.sln
  
skip_commits:
  message: /Driver/